"use client";

import { useState, useRef, useEffect } from "react";
import {
  MessageSquare, Send, X, Loader2, AlertTriangle,
  ChevronDown, ChevronUp, Sparkles, RefreshCw,
  Clock, Mail, MessageCircle, FileCheck
} from "lucide-react";

const API_BASE = "https://api.vsg-brain.com/api/info-hub";

interface BriefingItem {
  urgency: number;
  title: string;
  detail: string;
  source: string;
  reason: string;
  action: string;
  deadline?: string;
  related_emails?: string[];
}

interface Briefing {
  briefing_date: string;
  summary: string;
  items: BriefingItem[];
  stats: {
    total: number;
    critical: number;
    urgent: number;
    important: number;
  };
  email_index_map?: Record<string, string>;
}

interface Message {
  id: string;
  role: "user" | "assistant";
  content: string;
  briefing?: Briefing;
  timestamp: Date;
}

export default function BriefingAgentChat() {
  const [isOpen, setIsOpen] = useState(false);
  const [input, setInput] = useState("");
  const [messages, setMessages] = useState<Message[]>([]);
  const [isLoading, setIsLoading] = useState(false);
  const [currentBriefing, setCurrentBriefing] = useState<Briefing | null>(null);
  const [expandedItems, setExpandedItems] = useState<Record<number, boolean>>({});

  const messagesEndRef = useRef<HTMLDivElement>(null);
  const inputRef = useRef<HTMLInputElement>(null);
  const hasAutoGenerated = useRef(false);

  useEffect(() => {
    messagesEndRef.current?.scrollIntoView({ behavior: "smooth" });
  }, [messages]);

  useEffect(() => {
    if (isOpen && inputRef.current) {
      inputRef.current.focus();
    }
  }, [isOpen]);

  // Auto-generate briefing when opened
  useEffect(() => {
    if (isOpen && !hasAutoGenerated.current && messages.length === 0) {
      hasAutoGenerated.current = true;
      generateBriefing();
    }
  }, [isOpen]);

  // Generate urgency briefing
  const generateBriefing = async (regenerate = false) => {
    setIsLoading(true);

    const msgId = "system-" + new Date().getTime();
    const systemMsg: Message = {
      id: msgId,
      role: "assistant",
      content: regenerate ? "正在重新生成今日紧急简报..." : "正在生成今日紧急简报...",
      timestamp: new Date()
    };
    setMessages(prev => [...prev, systemMsg]);

    try {
      const token = localStorage.getItem("vulcan_token");
      const res = await fetch(`${API_BASE}/briefing/urgent?regenerate=${regenerate}`, {
        headers: token ? { "Authorization": `Bearer ${token}` } : {}
      });

      if (!res.ok) throw new Error(`服务器错误 ${res.status}`);

      const data = await res.json();

      if (data.error) {
        throw new Error(data.error);
      }

      const briefing = data.briefing as Briefing;
      setCurrentBriefing(briefing);

      const briefingMsg: Message = {
        id: "briefing-" + new Date().getTime(),
        role: "assistant",
        content: "",
        briefing: briefing,
        timestamp: new Date()
      };

      setMessages(prev => {
        const filtered = prev.filter(m => m.id !== msgId);
        return [...filtered, briefingMsg];
      });

    } catch (error: any) {
      const errorMsg: Message = {
        id: "error-" + new Date().getTime(),
        role: "assistant",
        content: `生成简报失败: ${error.message}`,
        timestamp: new Date()
      };
      setMessages(prev => {
        const filtered = prev.filter(m => m.id !== msgId);
        return [...filtered, errorMsg];
      });
    } finally {
      setIsLoading(false);
    }
  };

  // Send follow-up question
  const handleSend = async () => {
    if (!input.trim() || isLoading) return;

    const userMessage = input.trim();
    setInput("");

    const userMsg: Message = {
      id: "user-" + new Date().getTime(),
      role: "user",
      content: userMessage,
      timestamp: new Date()
    };
    setMessages(prev => [...prev, userMsg]);
    setIsLoading(true);

    try {
      const token = localStorage.getItem("vulcan_token");
      const res = await fetch(`${API_BASE}/briefing/chat`, {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          ...(token ? { "Authorization": `Bearer ${token}` } : {})
        },
        body: JSON.stringify({
          query: userMessage,
          briefing: currentBriefing
        })
      });

      if (!res.ok) throw new Error(`服务器错误 ${res.status}`);

      const data = await res.json();

      const assistantMsg: Message = {
        id: "assistant-" + new Date().getTime(),
        role: "assistant",
        content: data.answer || data.error || "无响应",
        timestamp: new Date()
      };
      setMessages(prev => [...prev, assistantMsg]);

    } catch (error: any) {
      const errorMsg: Message = {
        id: "error-" + new Date().getTime(),
        role: "assistant",
        content: `查询失败: ${error.message}`,
        timestamp: new Date()
      };
      setMessages(prev => [...prev, errorMsg]);
    } finally {
      setIsLoading(false);
    }
  };

  const handleKeyDown = (e: React.KeyboardEvent) => {
    if (e.key === "Enter" && !e.shiftKey) {
      e.preventDefault();
      handleSend();
    }
  };

  const toggleItem = (idx: number) => {
    setExpandedItems(prev => ({ ...prev, [idx]: !prev[idx] }));
  };

  // Urgency colors
  const getUrgencyColor = (urgency: number) => {
    if (urgency >= 5) return "text-red-400 bg-red-500/20 border-red-500/30";
    if (urgency >= 4) return "text-orange-400 bg-orange-500/20 border-orange-500/30";
    if (urgency >= 3) return "text-yellow-400 bg-yellow-500/20 border-yellow-500/30";
    if (urgency >= 2) return "text-blue-400 bg-blue-500/20 border-blue-500/30";
    return "text-zinc-400 bg-zinc-500/20 border-zinc-500/30";
  };

  const getUrgencyLabel = (urgency: number) => {
    if (urgency >= 5) return "极度紧急";
    if (urgency >= 4) return "紧急";
    if (urgency >= 3) return "重要";
    if (urgency >= 2) return "一般";
    return "低优";
  };

  const getSourceIcon = (source: string) => {
    switch (source) {
      case "email": return <Mail className="w-3 h-3" />;
      case "chat": return <MessageCircle className="w-3 h-3" />;
      case "approval": return <FileCheck className="w-3 h-3" />;
      default: return <AlertTriangle className="w-3 h-3" />;
    }
  };

  // Quick queries
  const quickQueries = [
    "哪些事项需要今天处理？",
    "有哪些VIP客户相关的事项？",
    "审批类事项有哪些？",
    "帮我生成一个处理计划"
  ];

  // Render briefing content
  const renderBriefing = (briefing: Briefing) => (
    <div className="space-y-3">
      {/* Summary */}
      <div className="p-3 bg-gradient-to-r from-orange-500/10 to-amber-500/10 border border-orange-500/20 rounded-lg">
        <p className="text-sm text-orange-200">{briefing.summary}</p>
        <div className="flex gap-4 mt-2 text-xs text-zinc-400">
          <span>共 {briefing.stats.total} 项</span>
          {briefing.stats.critical > 0 && <span className="text-red-400">极度紧急 {briefing.stats.critical}</span>}
          {briefing.stats.urgent > 0 && <span className="text-orange-400">紧急 {briefing.stats.urgent}</span>}
          {briefing.stats.important > 0 && <span className="text-yellow-400">重要 {briefing.stats.important}</span>}
        </div>
      </div>

      {/* Items list */}
      <div className="space-y-2 max-h-[300px] overflow-y-auto pr-1">
        {briefing.items.map((item, idx) => (
          <div
            key={idx}
            className={`border rounded-lg overflow-hidden ${getUrgencyColor(item.urgency)}`}
          >
            <button
              onClick={() => toggleItem(idx)}
              className="w-full p-2.5 flex items-start gap-2 text-left hover:bg-white/5 transition-colors"
            >
              <span className={`shrink-0 px-1.5 py-0.5 text-xs font-bold rounded ${getUrgencyColor(item.urgency)}`}>
                {item.urgency}
              </span>
              <div className="flex-1 min-w-0">
                <p className="text-sm font-medium truncate">{item.title}</p>
                <div className="flex items-center gap-2 mt-1 text-xs opacity-70">
                  {getSourceIcon(item.source)}
                  <span>{item.source}</span>
                  {item.deadline && (
                    <>
                      <Clock className="w-3 h-3 ml-1" />
                      <span>{item.deadline}</span>
                    </>
                  )}
                </div>
              </div>
              {expandedItems[idx] ? <ChevronUp className="w-4 h-4 shrink-0" /> : <ChevronDown className="w-4 h-4 shrink-0" />}
            </button>

            {expandedItems[idx] && (
              <div className="px-3 pb-3 pt-1 border-t border-white/10 text-xs space-y-2">
                <div>
                  <span className="text-zinc-500">详情：</span>
                  <span className="text-zinc-300">{item.detail}</span>
                </div>
                <div>
                  <span className="text-zinc-500">原因：</span>
                  <span className="text-zinc-300">{item.reason}</span>
                </div>
                <div>
                  <span className="text-zinc-500">建议：</span>
                  <span className="text-green-300">{item.action}</span>
                </div>
                {item.related_emails && item.related_emails.length > 0 && (
                  <div>
                    <span className="text-zinc-500">相关邮件：</span>
                    <span className="text-blue-300">{item.related_emails.join(", ")}</span>
                  </div>
                )}
              </div>
            )}
          </div>
        ))}
      </div>
    </div>
  );

  return (
    <>
      {/* Floating button */}
      <button
        onClick={() => setIsOpen(!isOpen)}
        className={`fixed bottom-6 right-6 z-50 w-14 h-14 rounded-full shadow-lg flex items-center justify-center transition-all ${
          isOpen
            ? "bg-zinc-800 text-zinc-400 hover:bg-zinc-700"
            : "bg-gradient-to-r from-red-500 to-orange-500 text-white hover:from-red-600 hover:to-orange-600 animate-pulse"
        }`}
        title="紧急简报"
      >
        {isOpen ? <X className="w-6 h-6" /> : <AlertTriangle className="w-6 h-6" />}
      </button>

      {/* Chat panel */}
      {isOpen && (
        <div className="fixed bottom-24 right-6 z-50 w-[440px] h-[620px] bg-zinc-900 rounded-2xl border border-zinc-800 shadow-2xl flex flex-col overflow-hidden">
          {/* Header */}
          <div className="flex items-center justify-between px-4 py-3 border-b border-zinc-800 bg-zinc-900/80 backdrop-blur">
            <div className="flex items-center gap-2">
              <div className="w-8 h-8 rounded-lg bg-gradient-to-br from-red-500 to-orange-500 flex items-center justify-center">
                <Sparkles className="w-4 h-4 text-white" />
              </div>
              <div>
                <h3 className="text-sm font-medium text-white">紧急简报助手</h3>
                <p className="text-xs text-zinc-500">智能分析今日待办事项</p>
              </div>
            </div>
            <button
              onClick={() => generateBriefing(true)}
              disabled={isLoading}
              className="p-2 text-zinc-400 hover:text-white hover:bg-zinc-800 rounded-lg transition-colors disabled:opacity-50"
              title="重新生成"
            >
              <RefreshCw className={`w-4 h-4 ${isLoading ? "animate-spin" : ""}`} />
            </button>
          </div>

          {/* Messages area */}
          <div className="flex-1 overflow-y-auto p-4 space-y-4">
            {messages.length === 0 && !isLoading ? (
              <div className="h-full flex flex-col items-center justify-center text-center">
                <AlertTriangle className="w-12 h-12 text-orange-500/50 mb-4" />
                <h4 className="text-sm font-medium text-zinc-300">紧急事项智能分析</h4>
                <p className="text-xs text-zinc-500 mt-1">正在加载...</p>
              </div>
            ) : (
              <>
                {messages.map((msg) => (
                  <div key={msg.id} className={`flex ${msg.role === "user" ? "justify-end" : "justify-start"}`}>
                    <div className={`max-w-[90%] ${
                      msg.role === "user"
                        ? "bg-orange-500/20 text-orange-100 border border-orange-500/30"
                        : "bg-zinc-800 text-zinc-200 border border-zinc-700"
                    } rounded-xl px-4 py-3`}>
                      {msg.briefing ? (
                        renderBriefing(msg.briefing)
                      ) : (
                        <p className="text-sm whitespace-pre-wrap">{msg.content}</p>
                      )}
                    </div>
                  </div>
                ))}

                {isLoading && (
                  <div className="flex justify-start">
                    <div className="bg-zinc-800 border border-zinc-700 rounded-xl px-4 py-3">
                      <Loader2 className="w-4 h-4 animate-spin text-orange-400" />
                    </div>
                  </div>
                )}
                <div ref={messagesEndRef} />
              </>
            )}

            {/* Quick queries */}
            {currentBriefing && !isLoading && (
              <div className="pt-2 border-t border-zinc-800">
                <p className="text-xs text-zinc-500 mb-2">快捷问题</p>
                <div className="flex flex-wrap gap-2">
                  {quickQueries.map((q, i) => (
                    <button
                      key={i}
                      onClick={() => setInput(q)}
                      className="px-2.5 py-1.5 text-xs text-zinc-400 bg-zinc-800/50 hover:bg-zinc-800 rounded-lg transition-colors"
                    >
                      {q}
                    </button>
                  ))}
                </div>
              </div>
            )}
          </div>

          {/* Input area */}
          <div className="p-4 border-t border-zinc-800 bg-zinc-900/80 backdrop-blur">
            <div className="flex items-center gap-2">
              <input
                ref={inputRef}
                type="text"
                value={input}
                onChange={(e) => setInput(e.target.value)}
                onKeyDown={handleKeyDown}
                placeholder="继续询问关于今日事项..."
                className="flex-1 px-4 py-2.5 bg-zinc-800 border border-zinc-700 rounded-xl text-sm text-white placeholder-zinc-500 focus:outline-none focus:border-orange-500/50"
                disabled={isLoading || !currentBriefing}
              />
              <button
                onClick={handleSend}
                disabled={!input.trim() || isLoading || !currentBriefing}
                className="p-2.5 bg-gradient-to-r from-red-500 to-orange-500 text-white rounded-xl disabled:opacity-50 disabled:cursor-not-allowed hover:from-red-600 hover:to-orange-600 transition-all"
              >
                <Send className="w-4 h-4" />
              </button>
            </div>
          </div>
        </div>
      )}
    </>
  );
}
